### ISSUE TITLE
BASIC Hell quine

### ISSUE THREAD

**Issue by MCausc78** [brainboxdotcc/retro-rocket#3]
when quote is not closed, interpreter for some reason prints source code of current running program
![image](https://user-images.githubusercontent.com/101461652/227772796-a0f7d48c-8219-43cd-a67e-1afe123f7b40.png)
(second image with hell, from D++ Discord server) ![image](https://user-images.githubusercontent.com/101461652/227772885-11c994ec-af1b-4671-910b-52b6dde5bd9e.png)

**Comment by braindigitalis** [comment]
fixed in 80a67fd
